package:
  name: starseqr
  version: "0.5.1"

source:
  fn: starseqr-0.5.1.tar.gz
  url: https://pypi.python.org/packages/9b/ec/94454022bd6fb7b198d335914ec3d43a9f322e63e29fb46f4b937bb37f49/starseqr-0.5.1.tar.gz
  md5: 58b7190543f93482a47d16bd79b2e88f

build:
  number: 0
  skip: False

requirements:
  build:
    - python
    - setuptools
    - cython
    - six
    - networkx
    - gcc # [linux]
    - llvm # [osx]
    - gffread
    - numpy
    - pandas >=0.18.1
    - pysam >=0.9.1.4
    - primer3-py
    - intervaltree_bio
    - biobambam # [linux]
    - star
    - velvet
    - ucsc-gtftogenepred
    - salmon

  run:
    - python
    - cython
    - six
    - networkx
    - gffread
    - pandas >=0.18.1
    - numpy
    - pysam >=0.9.1.4
    - primer3-py
    - intervaltree_bio
    - biobambam # [linux]
    - star
    - velvet
    - ucsc-gtftogenepred
    - salmon


test:
  imports:
    - ssw
    - starseqr_utils
    - starseqr_utils.tests

  requires:
    - nose

  commands:
    - starseqr.py -h

about:
  home: https://github.com/ExpressionAnalysis/STAR-SEQR
  license: https://github.com/ExpressionAnalysis/STAR-SEQR/blob/master/LICENSE
  summary: RNA Fusion Detection and Quantification
